/* ============================================================
   SHOP EASY – controllers/orderController.js
   Handles checkout and order history.
   ============================================================ */

const User  = require("../models/User");
const Order = require("../models/Order");

/* ── POST /api/orders ────────────────────────────────────────────
   Creates a new order from the user's current cart.
   - Takes a snapshot of all cart items
   - Calculates pricing
   - Saves the Order document
   - Adds order ref to User.orders
   - Clears the user's cart
*/
const createOrder = async (req, res) => {
  try {
    const user = await User.findById(req.user._id);

    // ── Guard: cart must not be empty ─────────────────────────
    if (!user.cart || user.cart.length === 0) {
      return res.status(400).json({ error: "Your cart is empty. Add items before checking out." });
    }

    // ── Pricing calculations ──────────────────────────────────
    const subtotal   = user.cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
    const delivery   = subtotal > 500 ? 0 : 49;          // Free delivery over ₹500
    const discount   = Math.round(subtotal * 0.05);       // 5% coupon
    const totalAmount = subtotal + delivery - discount;

    // ── Build order items snapshot ────────────────────────────
    // We store a copy of each item at current price
    // (so price changes later don't affect past orders)
    const items = user.cart.map(item => ({
      productId: item.productId,
      name:      item.name,
      price:     item.price,
      image:     item.image,
      category:  item.category,
      quantity:  item.quantity
    }));

    // ── Create the Order document ─────────────────────────────
    const order = await Order.create({
      userId:      user._id,
      items,
      subtotal,
      delivery,
      discount,
      totalAmount,
      status:      "Delivered"   // Demo: auto-delivered
      // orderId is auto-generated by the pre-save hook in Order.js
    });

    // ── Link order to user and clear cart ─────────────────────
    user.orders.push(order._id);
    user.cart = [];
    await user.save();

    res.status(201).json({
      message: "Order placed successfully!",
      order: {
        orderId:     order.orderId,
        items:       order.items,
        subtotal:    order.subtotal,
        delivery:    order.delivery,
        discount:    order.discount,
        totalAmount: order.totalAmount,
        status:      order.status,
        createdAt:   order.createdAt
      }
    });

  } catch (err) {
    console.error("Create order error:", err.message);
    res.status(500).json({ error: "Server error placing order." });
  }
};

/* ── GET /api/orders ─────────────────────────────────────────────
   Returns all orders for the logged-in user, newest first.
*/
const getUserOrders = async (req, res) => {
  try {
    const orders = await Order.find({ userId: req.user._id })
      .sort({ createdAt: -1 }); // Newest first

    res.json({
      count: orders.length,
      orders
    });

  } catch (err) {
    console.error("Get orders error:", err.message);
    res.status(500).json({ error: "Server error fetching orders." });
  }
};

/* ── GET /api/orders/:id ─────────────────────────────────────────
   Returns a single order by its MongoDB _id.
   User can only access their own orders.
*/
const getOrderById = async (req, res) => {
  try {
    const order = await Order.findOne({
      _id:    req.params.id,
      userId: req.user._id    // Ensures users can't see each other's orders
    });

    if (!order) {
      return res.status(404).json({ error: "Order not found." });
    }

    res.json({ order });

  } catch (err) {
    if (err.name === "CastError") {
      return res.status(400).json({ error: "Invalid order ID." });
    }
    console.error("Get order error:", err.message);
    res.status(500).json({ error: "Server error fetching order." });
  }
};

module.exports = { createOrder, getUserOrders, getOrderById };
